import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Two test pools:
    //   1. projectAssociation/ — pure TS, no Electron, no DB, no I/O
    //   2. electron/sync.test.ts — uses better-sqlite3 (Node-native), no Electron APIs
    include: [
      'electron/projectAssociation/**/*.test.ts',
      'electron/sync.test.ts',
      'electron/auth.test.ts',
      'electron/upload.test.ts',
      'electron/db.integration.test.ts',
      'electron/discovery.test.ts',
      'electron/security.test.ts',
      'electron/db.maintenance.test.ts',
      'electron/fs.benchmark.test.ts',
      'electron/association.test.ts',
      'electron/pending-resync.test.ts',
      'electron/deepLinkValidator.test.ts',
      'electron/iconAssets.test.ts',
      'electron/authLogging.test.ts',
      'electron/localStatusMigration.test.ts',
      'electron/preloadArgvParsing.test.ts',
      'electron/restore.security.test.ts',
      'electron/config.test.ts',
      'electron/syncScalability.test.ts',
      'electron/copilotTools/copilotTools.test.ts',
      'src/lib/folderAddFlow.test.ts',
      'src/lib/linksView.test.ts',
      'src/lib/projectDetailView.test.ts',
      'electron/links.test.ts',
      'electron/projectLinkService.test.ts',
      'electron/projectLinkHardening.test.ts',
      'electron/dbMigration.real.test.ts',
      'electron/native-sqlite.guard.test.ts',
      'electron/mediaProtocol.test.ts',
      'electron/adapters/adapters.test.ts',
      'src/lib/compatibilityView.test.ts',
      'src/dev/uiPreview/isPreviewEnabled.test.ts',
      'src/components/ui/uiPrimitives.test.ts',
      'src/lib/projectLinks.test.ts',
      'src/lib/accountContext.test.ts',
      'src/lib/codexLinkContractAdapter.test.ts',
      'electron/copilotTools/localTools.test.ts',
      'electron/copilotTools/assistantHardening.test.ts',
      'electron/copilotTools/assistantProjectLinks.test.ts',
      'src/lib/assistantToolCard.test.ts',
    ],
    environment: 'node',
  },
});
