import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Two test pools:
    //   1. projectAssociation/ — pure TS, no Electron, no DB, no I/O
    //   2. electron/sync.test.ts — uses better-sqlite3 (Node-native), no Electron APIs
    include: [
      'electron/projectAssociation/**/*.test.ts',
      'electron/sync.test.ts',
      'electron/auth.test.ts',
      'electron/upload.test.ts',
      'electron/db.integration.test.ts',
      'electron/discovery.test.ts',
      'electron/security.test.ts',
      'electron/db.maintenance.test.ts',
      'electron/fs.benchmark.test.ts',
      'electron/association.test.ts',
      'electron/pending-resync.test.ts',
      'electron/deepLinkValidator.test.ts',
      'electron/iconAssets.test.ts',
      'electron/authLogging.test.ts',
      'electron/localStatusMigration.test.ts',
      'electron/preloadArgvParsing.test.ts',
      'electron/restore.security.test.ts',
      'electron/config.test.ts',
      'electron/syncScalability.test.ts',
      'electron/copilotTools/copilotTools.test.ts',
      'src/lib/folderAddFlow.test.ts',
      'src/lib/linksView.test.ts',
      'src/lib/projectDetailView.test.ts',
      'electron/links.test.ts',
      'electron/projectLinkService.test.ts',
      'electron/projectLinkHardening.test.ts',
      'electron/dbMigration.real.test.ts',
      'electron/native-sqlite.guard.test.ts',
      'electron/mediaProtocol.test.ts',
      'electron/adapters/adapters.test.ts',
      'src/lib/compatibilityView.test.ts',
      'src/dev/uiPreview/isPreviewEnabled.test.ts',
      'src/components/ui/uiPrimitives.test.ts',
      'src/lib/projectLinks.test.ts',
      'src/lib/accountContext.test.ts',
      'src/lib/codexLinkContractAdapter.test.ts',
      'electron/copilotTools/localTools.test.ts',
      'electron/copilotTools/assistantHardening.test.ts',
      'electron/copilotTools/assistantProjectLinks.test.ts',
      'src/lib/assistantToolCard.test.ts',
      'electron/multiplayerContract.test.ts',
      'electron/multiplayerMembership.test.ts',
      'electron/multiplayerContribution.test.ts',
      'electron/multiplayerPrivacy.test.ts',
      'electron/multiplayerIdentity.test.ts',
      'electron/copilotTools/assistantMultiplayer.test.ts',
      'electron/multiplayerContributionQueue.test.ts',
      'electron/packagingHygiene.test.ts',
      'electron/stagingSmoke.test.ts',
      'src/lib/collaborationView.test.ts',
      'src/lib/designSystem.test.ts',
      'electron/coreWorkflow.integration.test.ts',
      'electron/restoreAdoption.test.ts',
      'electron/adapters/daws.test.ts',
      'electron/crossDaw.test.ts',
      'src/lib/returnAffordance.test.ts',
      'electron/brain/retrieval.test.ts',
      'electron/brain/memory.test.ts',
      'electron/brain/service.test.ts',
      'electron/brain/facts.real.test.ts',
      'electron/brain/derive.test.ts',
      'electron/copilotTools/brainTools.test.ts',
      'electron/brain/goldenPath.integration.test.ts',
      'electron/brain/scale.test.ts',
      'electron/brain/liveRefresh.test.ts',
      'electron/brain/liveRefresh.integration.test.ts',
      'electron/brain/fileLifecycle.real.test.ts',
      'electron/brain/liveGoldenPath.integration.test.ts',
      'electron/brain/activityView.test.ts',
      'electron/brain/legacyMemoryMigration.test.ts',
      'electron/brain/memoryUnification.real.test.ts',
      'electron/brain/recallMemory.test.ts',
      'electron/brain/recallMemory.real.test.ts',
      'electron/brain/assistantContext.test.ts',
      'electron/brain/contextGoldenPath.real.test.ts',
      'electron/brain/localAgent.test.ts',
      'electron/brain/localAgentStructured.test.ts',
      'electron/brain/agentActions.test.ts',
      'electron/brain/agentActionsContract.test.ts',
      'electron/brain/agentActionsV1.test.ts',
    ],
    environment: 'node',
  },
});
